apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: "mysecretpassword"
            - name: "MYSQL_DATABASE"
              value: "mydb"
            - name: "MYSQL_USER"
              value: "myuser"
            - name: "MYSQL_PASSWORD"
              value: "1234"
            - name: "MYSQL_TABLE"
              value: "data"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
